// pages/天尊计算/天尊计算.js
let interstitialAd = null
const app = getApp()
var databaseUtil = require('../../utils/dataBaseUtil')
const db = wx.cloud.database({
  env: databaseUtil.getDataBaseEnv()
})
Page({

  /**
   * 页面的初始数据
   */
  data: {
    bingzhongData:[
      {
        type:1,
        name:'近战骑'
      },
      {
        type:2,
        name:'骑射手'
      },
      {
        type:3,
        name:'弓兵'
      },
      {
        type:4,
        name:'弩兵'
      },
      {
        type:5,
        name:'枪兵'
      },
      {
        type:6,
        name:'盾兵'
      },
      {
        type:7,
        name:'投石'
      },
      {
        type:8,
        name:'攻城车'
      },
    ],
    shuxingData:[
      {
        type:1,
        name:'攻击'
      },
      {
        type:2,
        name:'防御'
      },
      {
        type:3,
        name:'生命'
      },
      {
        type:4,
        name:'攻击无视防御加成'
      },
      {
        type:5,
        name:'攻击无视生命加成'
      },
      {
        type:6,
        name:'伤害'
      },
      {
        type:7,
        name:'减伤'
      },
      {
        type:8,
        name:'冲锋时提高伤害',
        beforeName:"10级"
      },
      {
        type:9,
        name:'冲锋时提高攻击',
        beforeName:"10级"
      },
      {
        type:10,
        name:'重甲骑效果提高',
        beforeName:"10级",
        needEgnoreAdd:true
      },
      {
        type:11,
        name:'二叉箭头',
        beforeName:"11级",
      },
      {
        type:12,
        name:'骑兵受到近战伤害降低',
        needEgnoreAdd:true
      },
      {
        type:13,
        name:'鸿蒙基础攻击',
      },
      {
        type:14,
        name:'鸿蒙基础防御',
      },
      {
        type:15,
        name:'鸿蒙基础生命',
      },
      {
        type:16,
        name:'对远程伤害提高',
        unit:'次'
      },
      {
        type:17,
        name:'冲锋时提高伤害',
        beforeName:"12级"
      },
      {
        type:18,
        name:'冲锋时提高攻击',
        beforeName:"12级"
      },
      {
        type:19,
        name:'骑兵受到远程伤害降低',
        needEgnoreAdd:true,
      },
      {
        type:20,
        name:'骑射手每回合有概率标记目标，对其造成的伤害提高2.5倍',
        needEgnoreAdd:true,
      },
      {
        type:21,
        name:'骑射手每回合有概率标记目标，对其造成的伤害提高2.5倍',
        needEgnoreAdd:true,
      },
      {
        type:22,
        name:'伤害提高',
        beforeName:'11级'
      },
      {
        type:23,
        name:'伤害提高',
        beforeName:'13级'
      },
      {
        type:24,
        name:'攻击时无视生命',
        beforeName:'11级'
      },
      {
        type:25,
        name:'攻击时无视生命',
        beforeName:'13级'
      },
      {
        type:26,
        name:'全兵种攻击',
        needEgnoreAdd:true,
      },
      {
        type:27,
        name:'全兵种防御',
        needEgnoreAdd:true,
      },
      {
        type:28,
        name:'全兵种生命',
        needEgnoreAdd:true,
      },
    ],
    currentData:[],
    qibingData:[
      {
       index:0,
       title:'根骨',
       main:[
        {
          title:'乾坤',
          level:0,
          xingchenUnit:[70,130],
          qidiUnit:[40,70],
          tianzunUnit:[0,0],
          qishenUnit:[0,0],
          timeUnit:[50,60],
          isNeedQishen:false,
          shuxing:[{
            bingzhong:1,
            type:1,
            value:2
          }]
        },
        {
          title:'生始',
          level:0,
          xingchenUnit:[70,130],
          qidiUnit:[40,70],
          tianzunUnit:[0,0],
          qishenUnit:[0,0],
          timeUnit:[50,60],
          isNeedQishen:false,
          shuxing:[{
            bingzhong:1,
            type:2,
            value:2
          }]
        },
        {
          title:'载物',
          level:0,
          xingchenUnit:[70,130],
          qidiUnit:[40,70],
          tianzunUnit:[0,0],
          qishenUnit:[0,0],
          timeUnit:[50,60],
          isNeedQishen:false,
          shuxing:[{
            bingzhong:1,
            type:3,
            value:2
          }]
        },
        {
          title:'无疆',
          level:0,
          xingchenUnit:[90,160],
          qidiUnit:[50,90],
          tianzunUnit:[0,0],
          qishenUnit:[0,0],
          timeUnit:[60,70],
          isNeedQishen:false,
          shuxing:[{
            bingzhong:1,
            type:4,
            value:2
          }]
        },
        {
          title:'太和',
          level:0,
          xingchenUnit:[90,160],
          qidiUnit:[50,90],
          tianzunUnit:[0,0],
          qishenUnit:[0,0],
          timeUnit:[60,70],
          isNeedQishen:false,
          shuxing:[{
            bingzhong:1,
            type:5,
            value:2
          }]
        },
        {
          title:'庶物',
          level:0,
          xingchenUnit:[50,100],
          qidiUnit:[30,50],
          tianzunUnit:[300,400],
          qishenUnit:[0,0],
          timeUnit:[80,100],
          isNeedQishen:false,
          shuxing:[{
            bingzhong:1,
            type:6,
            value:1.5
          }]
        },
        {
          title:'流形',
          level:0,
          xingchenUnit:[50,100],
          qidiUnit:[30,50],
          tianzunUnit:[100,200],
          qishenUnit:[0,0],
          timeUnit:[80,100],
          isNeedQishen:false,
          shuxing:[
            {
              bingzhong:1,
              type:8,
              value:1.3
            },
            {
              bingzhong:1,
              type:9,
              value:0.8
            },
          ]
        },
        {
          title:'重战铁马',
          level:0,
          xingchenUnit:[0],
          qidiUnit:[0],
          tianzunUnit:[0],
          qishenUnit:[20,30,50,60,80],
          timeUnit:[0],
          isNeedQishen:true,
          shuxing:[
            {
              bingzhong:1,
              type:27,
              value:5
            },
            {
              bingzhong:1,
              type:28,
              value:5
            },
            {
              bingzhong:1,
              type:10,
              value:20
            },
          ]
        },
       ],
      },
      {
        title:'礼冠',
        index:1,
        main:[
          {
            title:'刚健',
            level:0,
            xingchenUnit:[70,130],
            qidiUnit:[40,70],
            tianzunUnit:[0,0],
            qishenUnit:[0,0],
            timeUnit:[50,60],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:2,
              type:1,
              value:2
            }]
          },
          {
            title:'满盈',
            level:0,
            xingchenUnit:[70,130],
            qidiUnit:[40,70],
            tianzunUnit:[0,0],
            qishenUnit:[0,0],
            timeUnit:[50,60],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:2,
              type:2,
              value:2
            }]
          },
          {
            title:'草昧',
            level:0,
            xingchenUnit:[70,130],
            qidiUnit:[40,70],
            tianzunUnit:[0,0],
            qishenUnit:[0,0],
            timeUnit:[50,60],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:2,
              type:3,
              value:2
            }]
          },
          {
            title:'建侯',
            level:0,
            xingchenUnit:[90,160],
            qidiUnit:[50,90],
            tianzunUnit:[0,0],
            qishenUnit:[0,0],
            timeUnit:[60,70],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:2,
              type:4,
              value:2
            }]
          },
          {
            title:'入渊',
            level:0,
            xingchenUnit:[90,160],
            qidiUnit:[50,90],
            tianzunUnit:[0,0],
            qishenUnit:[0,0],
            timeUnit:[60,70],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:2,
              type:5,
              value:2
            }]
          },
          {
            title:'涉川',
            level:0,
            xingchenUnit:[50,100],
            qidiUnit:[30,50],
            tianzunUnit:[300,400],
            qishenUnit:[0,0],
            timeUnit:[80,100],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:2,
              type:6,
              value:1.5
            }]
          },
          {
            title:'颂成',
            level:0,
            xingchenUnit:[50,100],
            qidiUnit:[30,50],
            tianzunUnit:[100,200],
            qishenUnit:[0,0],
            timeUnit:[80,100],
            isNeedQishen:false,
            shuxing:[
              {
                bingzhong:22,
                type:8,
                value:1
              },
              {
                bingzhong:24,
                type:9,
                value:0.5
              },
            ]
          },
          {
            title:'破军箭头',
            level:0,
            xingchenUnit:[0],
            qidiUnit:[0],
            tianzunUnit:[0],
            qishenUnit:[20,30,50,60,80],
            timeUnit:[0],
            isNeedQishen:true,
            shuxing:[
              {
                bingzhong:2,
                type:26,
                value:5
              },
              {
                bingzhong:2,
                type:11,
                value:20
              },
            ]
          },
         ],
       },
       {
        title:'尖切',
        index:2,
        main:[
          {
            title:'平心',
            levelMax:15,
            level:0,
            xingchenUnit:[310,590,1060],
            qidiUnit:[200,310,500],
            tianzunUnit:[0,0,0],
            qishenUnit:[0,0,0],
            timeUnit:[100,120,150],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:1,
              type:1,
              value:2
            },
            {
              bingzhong:1,
              type:2,
              value:2
            },
            {
              bingzhong:1,
              type:3,
              value:2
            }
            ]
          },
          {
            title:'残心',
            levelMax:15,
            level:0,
            xingchenUnit:[310,590,1060],
            qidiUnit:[200,310,500],
            tianzunUnit:[0,0,0],
            qishenUnit:[0,0,0],
            timeUnit:[100,120,150],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:2,
              type:1,
              value:2
            },
            {
              bingzhong:2,
              type:2,
              value:2
            },
            {
              bingzhong:2,
              type:3,
              value:2
            },
            ]
          },
          {
            title:'破军',
            isLock:true
          },
          {
            title:'镇国',
            levelMax:15,
            level:0,
            xingchenUnit:[880,1620,2030],
            qidiUnit:[370,490,610],
            tianzunUnit:[500,600,700],
            qishenUnit:[0,0,0],
            timeUnit:[200,250,300],
            isNeedQishen:false,
          },
          {
            title:'齐天',
            isLock:true
          },
          {
            title:'天尊骑风',
            isLock:true
          },
        ],
       },
       {
        index:3,
        title:'灵玉',
        main:[
          {
            title:'童蒙',
            levelMax:10,
            level:0,
            xingchenUnit:[640,850],
            qidiUnit:[300,400],
            tianzunUnit:[0,0],
            qishenUnit:[0,0],
            timeUnit:[120,120],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:1,
              type:2,
              value:3
            },
            {
              bingzhong:1,
              type:3,
              value:3
            },
            {
              bingzhong:2,
              type:2,
              value:3
            },
            {
              bingzhong:2,
              type:3,
              value:3
            },
            ]
          },
          {
            title:'健馔',
            levelMax:10,
            level:0,
            xingchenUnit:[640,850],
            qidiUnit:[300,370],
            tianzunUnit:[0,0],
            qishenUnit:[0,0],
            timeUnit:[120,150],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:1,
              bingzhongLevel:10,
              type:13,
              value:1.2
            },
            {
              bingzhong:1,
              bingzhongLevel:12,
              type:13,
              value:1.8
            }, 
            ]
          },
          {
            title:'虎尾',
            levelMax:10,
            level:0,
            xingchenUnit:[640,850],
            qidiUnit:[300,370],
            tianzunUnit:[0,0],
            qishenUnit:[0,0],
            timeUnit:[120,150],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:1,
              bingzhongLevel:10,
              type:14,
              value:1
            },
            {
              bingzhong:1,
              bingzhongLevel:12,
              type:14,
              value:1.5
            }, 
            ]
          },
          {
            title:'喰梦',
            levelMax:10,
            level:0,
            xingchenUnit:[640,880],
            qidiUnit:[300,370],
            tianzunUnit:[0,0],
            qishenUnit:[0,0],
            timeUnit:[120,150],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:1,
              bingzhongLevel:10,
              type:15,
              value:0.2
            },
            {
              bingzhong:1,
              bingzhongLevel:12,
              type:15,
              value:0.6
            }, 
            ]
          },
          {
            title:'殚心',
            levelMax:10,
            level:0,
            xingchenUnit:[160,160],
            qidiUnit:[70,70],
            tianzunUnit:[300,400],
            qishenUnit:[0,0],
            timeUnit:[150,175],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:1,
              type:12,
              value:1
            }
            ]
          },
          {
            title:'无咎',
            levelMax:10,
            level:0,
            xingchenUnit:[270,680],
            qidiUnit:[120,200],
            tianzunUnit:[600,900],
            qishenUnit:[0,0],
            timeUnit:[200,300],
            isNeedQishen:false,
          },
          {
            title:'青龙马术',
            isLock:true
          },
        ],
       },
       {
        index:4,
        title:'绰韬',
        main:[
          {
            title:'伟岸',
            levelMax:10,
            level:0,
            xingchenUnit:[440,590],
            qidiUnit:[190,250],
            tianzunUnit:[0,0],
            qishenUnit:[0,0],
            timeUnit:[120,150],
            isNeedQishen:false,
          },
          {
            title:'鸿土',
            isLock:true
          },
          {
            title:'睚眦',
            isLock:true
          },
          {
            title:'毕呈',
            isLock:true
          },
          {
            title:'盖世',
            isLock:true
          },
          {
            title:'传胤',
            isLock:true
          },
          {
            title:'青龙箭头',
            isLock:true
          },
        ],
       },
    ],
    gongnuData:[
      {
       index:0,
       title:'根骨',
       main:[
        {
          title:'乾坤',
          level:0,
          xingchenUnit:[70,130],
          qidiUnit:[40,70],
          tianzunUnit:[0,0],
          qishenUnit:[0,0],
          timeUnit:[50,60],
          isNeedQishen:false,
          shuxing:[{
            bingzhong:1,
            type:1,
            value:2
          }]
        },
        {
          title:'生始',
          level:0,
          xingchenUnit:[70,130],
          qidiUnit:[40,70],
          tianzunUnit:[0,0],
          qishenUnit:[0,0],
          timeUnit:[50,60],
          isNeedQishen:false,
          shuxing:[{
            bingzhong:1,
            type:2,
            value:2
          }]
        },
        {
          title:'载物',
          level:0,
          xingchenUnit:[70,130],
          qidiUnit:[40,70],
          tianzunUnit:[0,0],
          qishenUnit:[0,0],
          timeUnit:[50,60],
          isNeedQishen:false,
          shuxing:[{
            bingzhong:1,
            type:3,
            value:2
          }]
        },
        {
          title:'无疆',
          level:0,
          xingchenUnit:[90,160],
          qidiUnit:[50,90],
          tianzunUnit:[0,0],
          qishenUnit:[0,0],
          timeUnit:[60,70],
          isNeedQishen:false,
          shuxing:[{
            bingzhong:1,
            type:4,
            value:2
          }]
        },
        {
          title:'太和',
          level:0,
          xingchenUnit:[90,160],
          qidiUnit:[50,90],
          tianzunUnit:[0,0],
          qishenUnit:[0,0],
          timeUnit:[60,70],
          isNeedQishen:false,
          shuxing:[{
            bingzhong:1,
            type:5,
            value:2
          }]
        },
        {
          title:'庶物',
          level:0,
          xingchenUnit:[50,100],
          qidiUnit:[30,50],
          tianzunUnit:[300,400],
          qishenUnit:[0,0],
          timeUnit:[80,100],
          isNeedQishen:false,
          shuxing:[{
            bingzhong:1,
            type:6,
            value:1.5
          }]
        },
        {
          title:'流形',
          level:0,
          xingchenUnit:[50,100],
          qidiUnit:[30,50],
          tianzunUnit:[100,200],
          qishenUnit:[0,0],
          timeUnit:[80,100],
          isNeedQishen:false,
          shuxing:[
            {
              bingzhong:1,
              type:8,
              value:1.3
            },
            {
              bingzhong:1,
              type:9,
              value:0.8
            },
          ]
        },
        {
          title:'火药研发',
          level:0,
          xingchenUnit:[0],
          qidiUnit:[0],
          tianzunUnit:[0],
          qishenUnit:[20,30,50,60,80],
          timeUnit:[0],
          isNeedQishen:true,
          shuxing:[
            {
              bingzhong:1,
              type:27,
              value:5
            },
            {
              bingzhong:1,
              type:28,
              value:5
            },
            {
              bingzhong:1,
              type:10,
              value:20
            },
          ]
        },
       ],
      },
      {
        title:'礼冠',
        index:1,
        main:[
          {
            title:'刚健',
            level:0,
            xingchenUnit:[70,130],
            qidiUnit:[40,70],
            tianzunUnit:[0,0],
            qishenUnit:[0,0],
            timeUnit:[50,60],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:2,
              type:1,
              value:2
            }]
          },
          {
            title:'满盈',
            level:0,
            xingchenUnit:[70,130],
            qidiUnit:[40,70],
            tianzunUnit:[0,0],
            qishenUnit:[0,0],
            timeUnit:[50,60],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:2,
              type:2,
              value:2
            }]
          },
          {
            title:'草昧',
            level:0,
            xingchenUnit:[70,130],
            qidiUnit:[40,70],
            tianzunUnit:[0,0],
            qishenUnit:[0,0],
            timeUnit:[50,60],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:2,
              type:3,
              value:2
            }]
          },
          {
            title:'建侯',
            level:0,
            xingchenUnit:[90,160],
            qidiUnit:[50,90],
            tianzunUnit:[0,0],
            qishenUnit:[0,0],
            timeUnit:[60,70],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:2,
              type:4,
              value:2
            }]
          },
          {
            title:'入渊',
            level:0,
            xingchenUnit:[90,160],
            qidiUnit:[50,90],
            tianzunUnit:[0,0],
            qishenUnit:[0,0],
            timeUnit:[60,70],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:2,
              type:5,
              value:2
            }]
          },
          {
            title:'涉川',
            level:0,
            xingchenUnit:[50,100],
            qidiUnit:[30,50],
            tianzunUnit:[300,400],
            qishenUnit:[0,0],
            timeUnit:[80,100],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:2,
              type:6,
              value:1.5
            }]
          },
          {
            title:'颂成',
            level:0,
            xingchenUnit:[50,100],
            qidiUnit:[30,50],
            tianzunUnit:[100,200],
            qishenUnit:[0,0],
            timeUnit:[80,100],
            isNeedQishen:false,
            shuxing:[
              {
                bingzhong:22,
                type:8,
                value:1
              },
              {
                bingzhong:24,
                type:9,
                value:0.5
              },
            ]
          },
          {
            title:'机关弩术',
            level:0,
            xingchenUnit:[0],
            qidiUnit:[0],
            tianzunUnit:[0],
            qishenUnit:[20,30,50,60,80],
            timeUnit:[0],
            isNeedQishen:true,
            shuxing:[
              {
                bingzhong:2,
                type:26,
                value:5
              },
              {
                bingzhong:2,
                type:11,
                value:20
              },
            ]
          },
         ],
       },
       {
        title:'尖切',
        index:2,
        main:[
          {
            title:'平心',
            levelMax:15,
            level:0,
            xingchenUnit:[310,590,1060],
            qidiUnit:[200,310,500],
            tianzunUnit:[0,0,0],
            qishenUnit:[0,0,0],
            timeUnit:[100,120,150],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:1,
              type:1,
              value:2
            },
            {
              bingzhong:1,
              type:2,
              value:2
            },
            {
              bingzhong:1,
              type:3,
              value:2
            }
            ]
          },
          {
            title:'残心',
            levelMax:15,
            level:0,
            xingchenUnit:[310,590,1060],
            qidiUnit:[200,310,500],
            tianzunUnit:[0,0,0],
            qishenUnit:[0,0,0],
            timeUnit:[100,120,150],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:2,
              type:1,
              value:2
            },
            {
              bingzhong:2,
              type:2,
              value:2
            },
            {
              bingzhong:2,
              type:3,
              value:2
            },
            ]
          },
          {
            title:'破军',
            isLock:true
          },
          {
            title:'镇国',
            levelMax:15,
            level:0,
            xingchenUnit:[880,1620,2030],
            qidiUnit:[370,490,610],
            tianzunUnit:[500,600,700],
            qishenUnit:[0,0,0],
            timeUnit:[200,250,300],
            isNeedQishen:false,
          },
          {
            title:'齐天',
            isLock:true
          },
          {
            title:'天尊御射',
            isLock:true
          },
        ],
       },
       {
        index:3,
        title:'灵玉',
        main:[
          {
            title:'童蒙',
            levelMax:10,
            level:0,
            xingchenUnit:[640,850],
            qidiUnit:[300,400],
            tianzunUnit:[0,0],
            qishenUnit:[0,0],
            timeUnit:[120,120],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:1,
              type:2,
              value:3
            },
            {
              bingzhong:1,
              type:3,
              value:3
            },
            {
              bingzhong:2,
              type:2,
              value:3
            },
            {
              bingzhong:2,
              type:3,
              value:3
            },
            ]
          },
          {
            title:'健馔',
            levelMax:10,
            level:0,
            xingchenUnit:[640,850],
            qidiUnit:[300,370],
            tianzunUnit:[0,0],
            qishenUnit:[0,0],
            timeUnit:[120,150],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:1,
              bingzhongLevel:10,
              type:13,
              value:1.2
            },
            {
              bingzhong:1,
              bingzhongLevel:12,
              type:13,
              value:1.8
            }, 
            ]
          },
          {
            title:'虎尾',
            levelMax:10,
            level:0,
            xingchenUnit:[640,850],
            qidiUnit:[300,370],
            tianzunUnit:[0,0],
            qishenUnit:[0,0],
            timeUnit:[120,150],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:1,
              bingzhongLevel:10,
              type:14,
              value:1
            },
            {
              bingzhong:1,
              bingzhongLevel:12,
              type:14,
              value:1.5
            }, 
            ]
          },
          {
            title:'喰梦',
            levelMax:10,
            level:0,
            xingchenUnit:[640,850],
            qidiUnit:[300,370],
            tianzunUnit:[0,0],
            qishenUnit:[0,0],
            timeUnit:[120,150],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:1,
              bingzhongLevel:10,
              type:15,
              value:0.2
            },
            {
              bingzhong:1,
              bingzhongLevel:12,
              type:15,
              value:0.6
            }, 
            ]
          },
          {
            title:'殚心',
            levelMax:10,
            level:0,
            xingchenUnit:[160,160],
            qidiUnit:[70,70],
            tianzunUnit:[300,400],
            qishenUnit:[0,0],
            timeUnit:[150,175],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:1,
              type:12,
              value:1
            }
            ]
          },
          {
            title:'无咎',
            levelMax:10,
            level:0,
            xingchenUnit:[270,680],
            qidiUnit:[120,200],
            tianzunUnit:[600,900],
            qishenUnit:[0,0],
            timeUnit:[200,300],
            isNeedQishen:false,
          },
          {
            title:'朱雀引信',
            isLock:true
          },
        ],
       },
       {
        index:4,
        title:'绰韬',
        main:[
          {
            title:'伟岸',
            levelMax:10,
            level:0,
            xingchenUnit:[440,590],
            qidiUnit:[190,250],
            tianzunUnit:[0,0],
            qishenUnit:[0,0],
            timeUnit:[120,150],
            isNeedQishen:false,
          },
          {
            title:'鸿土',
            isLock:true
          },
          {
            title:'睚眦',
            isLock:true
          },
          {
            title:'毕呈',
            isLock:true
          },
          {
            title:'盖世',
            isLock:true
          },
          {
            title:'传胤',
            isLock:true
          },
          {
            title:'朱雀机关',
            isLock:true
          },
        ],
       },
    ],
    bubingData:[
      {
       index:0,
       title:'根骨',
       main:[
        {
          title:'乾坤',
          level:0,
          xingchenUnit:[70,130],
          qidiUnit:[40,70],
          tianzunUnit:[0,0],
          qishenUnit:[0,0],
          timeUnit:[50,60],
          isNeedQishen:false,
          shuxing:[{
            bingzhong:1,
            type:1,
            value:2
          }]
        },
        {
          title:'生始',
          level:0,
          xingchenUnit:[70,130],
          qidiUnit:[40,70],
          tianzunUnit:[0,0],
          qishenUnit:[0,0],
          timeUnit:[50,60],
          isNeedQishen:false,
          shuxing:[{
            bingzhong:1,
            type:2,
            value:2
          }]
        },
        {
          title:'载物',
          level:0,
          xingchenUnit:[70,130],
          qidiUnit:[40,70],
          tianzunUnit:[0,0],
          qishenUnit:[0,0],
          timeUnit:[50,60],
          isNeedQishen:false,
          shuxing:[{
            bingzhong:1,
            type:3,
            value:2
          }]
        },
        {
          title:'无疆',
          level:0,
          xingchenUnit:[90,160],
          qidiUnit:[50,90],
          tianzunUnit:[0,0],
          qishenUnit:[0,0],
          timeUnit:[60,70],
          isNeedQishen:false,
          shuxing:[{
            bingzhong:1,
            type:4,
            value:2
          }]
        },
        {
          title:'太和',
          level:0,
          xingchenUnit:[90,160],
          qidiUnit:[50,90],
          tianzunUnit:[0,0],
          qishenUnit:[0,0],
          timeUnit:[60,70],
          isNeedQishen:false,
          shuxing:[{
            bingzhong:1,
            type:5,
            value:2
          }]
        },
        {
          title:'庶物',
          level:0,
          xingchenUnit:[50,100],
          qidiUnit:[30,50],
          tianzunUnit:[300,400],
          qishenUnit:[0,0],
          timeUnit:[80,100],
          isNeedQishen:false,
          shuxing:[{
            bingzhong:1,
            type:6,
            value:1.5
          }]
        },
        {
          title:'流形',
          level:0,
          xingchenUnit:[50,100],
          qidiUnit:[30,50],
          tianzunUnit:[100,200],
          qishenUnit:[0,0],
          timeUnit:[80,100],
          isNeedQishen:false,
          shuxing:[
            {
              bingzhong:1,
              type:8,
              value:1.3
            },
            {
              bingzhong:1,
              type:9,
              value:0.8
            },
          ]
        },
        {
          title:'列盾御法',
          level:0,
          xingchenUnit:[0],
          qidiUnit:[0],
          tianzunUnit:[0],
          qishenUnit:[20,30,50,60,80],
          timeUnit:[0],
          isNeedQishen:true,
          shuxing:[
            {
              bingzhong:1,
              type:27,
              value:5
            },
            {
              bingzhong:1,
              type:28,
              value:5
            },
            {
              bingzhong:1,
              type:10,
              value:20
            },
          ]
        },
       ],
      },
      {
        title:'礼冠',
        index:1,
        main:[
          {
            title:'刚健',
            level:0,
            xingchenUnit:[70,130],
            qidiUnit:[40,70],
            tianzunUnit:[0,0],
            qishenUnit:[0,0],
            timeUnit:[50,60],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:2,
              type:1,
              value:2
            }]
          },
          {
            title:'满盈',
            level:0,
            xingchenUnit:[70,130],
            qidiUnit:[40,70],
            tianzunUnit:[0,0],
            qishenUnit:[0,0],
            timeUnit:[50,60],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:2,
              type:2,
              value:2
            }]
          },
          {
            title:'草昧',
            level:0,
            xingchenUnit:[70,130],
            qidiUnit:[40,70],
            tianzunUnit:[0,0],
            qishenUnit:[0,0],
            timeUnit:[50,60],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:2,
              type:3,
              value:2
            }]
          },
          {
            title:'建侯',
            level:0,
            xingchenUnit:[90,160],
            qidiUnit:[50,90],
            tianzunUnit:[0,0],
            qishenUnit:[0,0],
            timeUnit:[60,70],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:2,
              type:4,
              value:2
            }]
          },
          {
            title:'入渊',
            level:0,
            xingchenUnit:[90,160],
            qidiUnit:[50,90],
            tianzunUnit:[0,0],
            qishenUnit:[0,0],
            timeUnit:[60,70],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:2,
              type:5,
              value:2
            }]
          },
          {
            title:'涉川',
            level:0,
            xingchenUnit:[50,100],
            qidiUnit:[30,50],
            tianzunUnit:[300,400],
            qishenUnit:[0,0],
            timeUnit:[80,100],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:2,
              type:6,
              value:1.5
            }]
          },
          {
            title:'颂成',
            level:0,
            xingchenUnit:[50,100],
            qidiUnit:[30,50],
            tianzunUnit:[100,200],
            qishenUnit:[0,0],
            timeUnit:[80,100],
            isNeedQishen:false,
            shuxing:[
              {
                bingzhong:22,
                type:8,
                value:1
              },
              {
                bingzhong:24,
                type:9,
                value:0.5
              },
            ]
          },
          {
            title:'北国锻术',
            level:0,
            xingchenUnit:[0],
            qidiUnit:[0],
            tianzunUnit:[0],
            qishenUnit:[20,30,50,60,80],
            timeUnit:[0],
            isNeedQishen:true,
            shuxing:[
              {
                bingzhong:2,
                type:26,
                value:5
              },
              {
                bingzhong:2,
                type:11,
                value:20
              },
            ]
          },
         ],
       },
       {
        title:'尖切',
        index:2,
        main:[
          {
            title:'平心',
            levelMax:15,
            level:0,
            xingchenUnit:[310,590,1060],
            qidiUnit:[200,310,500],
            tianzunUnit:[0,0,0],
            qishenUnit:[0,0,0],
            timeUnit:[100,120,150],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:1,
              type:1,
              value:2
            },
            {
              bingzhong:1,
              type:2,
              value:2
            },
            {
              bingzhong:1,
              type:3,
              value:2
            }
            ]
          },
          {
            title:'残心',
            levelMax:15,
            level:0,
            xingchenUnit:[310,590,1060],
            qidiUnit:[200,310,500],
            tianzunUnit:[0,0,0],
            qishenUnit:[0,0,0],
            timeUnit:[100,120,150],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:2,
              type:1,
              value:2
            },
            {
              bingzhong:2,
              type:2,
              value:2
            },
            {
              bingzhong:2,
              type:3,
              value:2
            },
            ]
          },
          {
            title:'破军',
            isLock:true
          },
          {
            title:'镇国',
            levelMax:15,
            level:0,
            xingchenUnit:[880,1620,2030],
            qidiUnit:[370,490,610],
            tianzunUnit:[500,600,700],
            qishenUnit:[0,0,0],
            timeUnit:[200,250,300],
            isNeedQishen:false,
          },
          {
            title:'齐天',
            isLock:true
          },
          {
            title:'天尊战歌',
            isLock:true
          },
        ],
       },
       {
        index:3,
        title:'灵玉',
        main:[
          {
            title:'童蒙',
            levelMax:10,
            level:0,
            xingchenUnit:[640,850],
            qidiUnit:[300,400],
            tianzunUnit:[0,0],
            qishenUnit:[0,0],
            timeUnit:[120,120],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:1,
              type:2,
              value:3
            },
            {
              bingzhong:1,
              type:3,
              value:3
            },
            {
              bingzhong:2,
              type:2,
              value:3
            },
            {
              bingzhong:2,
              type:3,
              value:3
            },
            ]
          },
          {
            title:'健馔',
            levelMax:10,
            level:0,
            xingchenUnit:[640,850],
            qidiUnit:[300,370],
            tianzunUnit:[0,0],
            qishenUnit:[0,0],
            timeUnit:[120,150],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:1,
              bingzhongLevel:10,
              type:13,
              value:1.2
            },
            {
              bingzhong:1,
              bingzhongLevel:12,
              type:13,
              value:1.8
            }, 
            ]
          },
          {
            title:'虎尾',
            levelMax:10,
            level:0,
            xingchenUnit:[640,850],
            qidiUnit:[300,370],
            tianzunUnit:[0,0],
            qishenUnit:[0,0],
            timeUnit:[120,150],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:1,
              bingzhongLevel:10,
              type:14,
              value:1
            },
            {
              bingzhong:1,
              bingzhongLevel:12,
              type:14,
              value:1.5
            }, 
            ]
          },
          {
            title:'喰梦',
            levelMax:10,
            level:0,
            xingchenUnit:[640,850],
            qidiUnit:[300,370],
            tianzunUnit:[0,0],
            qishenUnit:[0,0],
            timeUnit:[120,150],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:1,
              bingzhongLevel:10,
              type:15,
              value:0.2
            },
            {
              bingzhong:1,
              bingzhongLevel:12,
              type:15,
              value:0.6
            }, 
            ]
          },
          {
            title:'殚心',
            levelMax:10,
            level:0,
            xingchenUnit:[160,160],
            qidiUnit:[70,70],
            tianzunUnit:[300,400],
            qishenUnit:[0,0],
            timeUnit:[150,175],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:1,
              type:12,
              value:1
            }
            ]
          },
          {
            title:'无咎',
            levelMax:10,
            level:0,
            xingchenUnit:[270,680],
            qidiUnit:[120,200],
            tianzunUnit:[600,900],
            qishenUnit:[0,0],
            timeUnit:[200,300],
            isNeedQishen:false,
          },
          {
            title:'白虎御法',
            isLock:true
          },
        ],
       },
       {
        index:4,
        title:'绰韬',
        main:[
          {
            title:'伟岸',
            levelMax:10,
            level:0,
            xingchenUnit:[440,590],
            qidiUnit:[190,250],
            tianzunUnit:[0,0],
            qishenUnit:[0,0],
            timeUnit:[120,150],
            isNeedQishen:false,
          },
          {
            title:'鸿土',
            isLock:true
          },
          {
            title:'睚眦',
            isLock:true
          },
          {
            title:'毕呈',
            isLock:true
          },
          {
            title:'盖世',
            isLock:true
          },
          {
            title:'传胤',
            isLock:true
          },
          {
            title:'白虎锻术',
            isLock:true
          },
        ],
       },
    ],
    chebingData:[
      {
       index:0,
       title:'根骨',
       main:[
        {
          title:'乾坤',
          level:0,
          xingchenUnit:[70,130],
          qidiUnit:[40,70],
          tianzunUnit:[0,0],
          qishenUnit:[0,0],
          timeUnit:[50,60],
          isNeedQishen:false,
          shuxing:[{
            bingzhong:1,
            type:1,
            value:2
          }]
        },
        {
          title:'生始',
          level:0,
          xingchenUnit:[70,130],
          qidiUnit:[40,70],
          tianzunUnit:[0,0],
          qishenUnit:[0,0],
          timeUnit:[50,60],
          isNeedQishen:false,
          shuxing:[{
            bingzhong:1,
            type:2,
            value:2
          }]
        },
        {
          title:'载物',
          level:0,
          xingchenUnit:[70,130],
          qidiUnit:[40,70],
          tianzunUnit:[0,0],
          qishenUnit:[0,0],
          timeUnit:[50,60],
          isNeedQishen:false,
          shuxing:[{
            bingzhong:1,
            type:3,
            value:2
          }]
        },
        {
          title:'无疆',
          level:0,
          xingchenUnit:[90,160],
          qidiUnit:[50,90],
          tianzunUnit:[0,0],
          qishenUnit:[0,0],
          timeUnit:[60,70],
          isNeedQishen:false,
          shuxing:[{
            bingzhong:1,
            type:4,
            value:2
          }]
        },
        {
          title:'太和',
          level:0,
          xingchenUnit:[90,160],
          qidiUnit:[50,90],
          tianzunUnit:[0,0],
          qishenUnit:[0,0],
          timeUnit:[60,70],
          isNeedQishen:false,
          shuxing:[{
            bingzhong:1,
            type:5,
            value:2
          }]
        },
        {
          title:'庶物',
          level:0,
          xingchenUnit:[50,100],
          qidiUnit:[30,50],
          tianzunUnit:[300,400],
          qishenUnit:[0,0],
          timeUnit:[80,100],
          isNeedQishen:false,
          shuxing:[{
            bingzhong:1,
            type:6,
            value:1.5
          }]
        },
        {
          title:'流形',
          level:0,
          xingchenUnit:[50,100],
          qidiUnit:[30,50],
          tianzunUnit:[100,200],
          qishenUnit:[0,0],
          timeUnit:[80,100],
          isNeedQishen:false,
          shuxing:[
            {
              bingzhong:1,
              type:8,
              value:1.3
            },
            {
              bingzhong:1,
              type:9,
              value:0.8
            },
          ]
        },
        {
          title:'重型弹药',
          level:0,
          xingchenUnit:[0],
          qidiUnit:[0],
          tianzunUnit:[0],
          qishenUnit:[20,30,50,60,80],
          timeUnit:[0],
          isNeedQishen:true,
          shuxing:[
            {
              bingzhong:1,
              type:27,
              value:5
            },
            {
              bingzhong:1,
              type:28,
              value:5
            },
            {
              bingzhong:1,
              type:10,
              value:20
            },
          ]
        },
       ],
      },
      {
        title:'礼冠',
        index:1,
        main:[
          {
            title:'刚健',
            level:0,
            xingchenUnit:[70,130],
            qidiUnit:[40,70],
            tianzunUnit:[0,0],
            qishenUnit:[0,0],
            timeUnit:[50,60],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:2,
              type:1,
              value:2
            }]
          },
          {
            title:'满盈',
            level:0,
            xingchenUnit:[70,130],
            qidiUnit:[40,70],
            tianzunUnit:[0,0],
            qishenUnit:[0,0],
            timeUnit:[50,60],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:2,
              type:2,
              value:2
            }]
          },
          {
            title:'草昧',
            level:0,
            xingchenUnit:[70,130],
            qidiUnit:[40,70],
            tianzunUnit:[0,0],
            qishenUnit:[0,0],
            timeUnit:[50,60],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:2,
              type:3,
              value:2
            }]
          },
          {
            title:'建侯',
            level:0,
            xingchenUnit:[90,160],
            qidiUnit:[50,90],
            tianzunUnit:[0,0],
            qishenUnit:[0,0],
            timeUnit:[60,70],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:2,
              type:4,
              value:2
            }]
          },
          {
            title:'入渊',
            level:0,
            xingchenUnit:[90,160],
            qidiUnit:[50,90],
            tianzunUnit:[0,0],
            qishenUnit:[0,0],
            timeUnit:[60,70],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:2,
              type:5,
              value:2
            }]
          },
          {
            title:'涉川',
            level:0,
            xingchenUnit:[50,100],
            qidiUnit:[30,50],
            tianzunUnit:[300,400],
            qishenUnit:[0,0],
            timeUnit:[80,100],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:2,
              type:6,
              value:1.5
            }]
          },
          {
            title:'颂成',
            level:0,
            xingchenUnit:[50,100],
            qidiUnit:[30,50],
            tianzunUnit:[100,200],
            qishenUnit:[0,0],
            timeUnit:[80,100],
            isNeedQishen:false,
            shuxing:[
              {
                bingzhong:22,
                type:8,
                value:1
              },
              {
                bingzhong:24,
                type:9,
                value:0.5
              },
            ]
          },
          {
            title:'御甲战术',
            level:0,
            xingchenUnit:[0],
            qidiUnit:[0],
            tianzunUnit:[0],
            qishenUnit:[20,30,50,60,80],
            timeUnit:[0],
            isNeedQishen:true,
            shuxing:[
              {
                bingzhong:2,
                type:26,
                value:5
              },
              {
                bingzhong:2,
                type:11,
                value:20
              },
            ]
          },
         ],
       },
       {
        title:'尖切',
        index:2,
        main:[
          {
            title:'平心',
            levelMax:15,
            level:0,
            xingchenUnit:[310,590,1060],
            qidiUnit:[200,310,500],
            tianzunUnit:[0,0,0],
            qishenUnit:[0,0,0],
            timeUnit:[100,120,150],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:1,
              type:1,
              value:2
            },
            {
              bingzhong:1,
              type:2,
              value:2
            },
            {
              bingzhong:1,
              type:3,
              value:2
            }
            ]
          },
          {
            title:'残心',
            levelMax:15,
            level:0,
            xingchenUnit:[310,590,1060],
            qidiUnit:[200,310,500],
            tianzunUnit:[0,0,0],
            qishenUnit:[0,0,0],
            timeUnit:[100,120,150],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:2,
              type:1,
              value:2
            },
            {
              bingzhong:2,
              type:2,
              value:2
            },
            {
              bingzhong:2,
              type:3,
              value:2
            },
            ]
          },
          {
            title:'破军',
            isLock:true
          },
          {
            title:'镇国',
            levelMax:15,
            level:0,
            xingchenUnit:[880,1620,2030],
            qidiUnit:[370,490,610],
            tianzunUnit:[500,600,700],
            qishenUnit:[0,0,0],
            timeUnit:[200,250,300],
            isNeedQishen:false,
          },
          {
            title:'齐天',
            isLock:true
          },
          {
            title:'天尊破城',
            isLock:true
          },
        ],
       },
       {
        index:3,
        title:'灵玉',
        main:[
          {
            title:'童蒙',
            levelMax:10,
            level:0,
            xingchenUnit:[640,850],
            qidiUnit:[300,400],
            tianzunUnit:[0,0],
            qishenUnit:[0,0],
            timeUnit:[120,120],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:1,
              type:2,
              value:3
            },
            {
              bingzhong:1,
              type:3,
              value:3
            },
            {
              bingzhong:2,
              type:2,
              value:3
            },
            {
              bingzhong:2,
              type:3,
              value:3
            },
            ]
          },
          {
            title:'健馔',
            levelMax:10,
            level:0,
            xingchenUnit:[640,850],
            qidiUnit:[300,370],
            tianzunUnit:[0,0],
            qishenUnit:[0,0],
            timeUnit:[120,150],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:1,
              bingzhongLevel:10,
              type:13,
              value:1.2
            },
            {
              bingzhong:1,
              bingzhongLevel:12,
              type:13,
              value:1.8
            }, 
            ]
          },
          {
            title:'虎尾',
            levelMax:10,
            level:0,
            xingchenUnit:[640,850],
            qidiUnit:[300,370],
            tianzunUnit:[0,0],
            qishenUnit:[0,0],
            timeUnit:[120,150],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:1,
              bingzhongLevel:10,
              type:14,
              value:1
            },
            {
              bingzhong:1,
              bingzhongLevel:12,
              type:14,
              value:1.5
            }, 
            ]
          },
          {
            title:'喰梦',
            levelMax:10,
            level:0,
            xingchenUnit:[640,850],
            qidiUnit:[300,370],
            tianzunUnit:[0,0],
            qishenUnit:[0,0],
            timeUnit:[120,150],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:1,
              bingzhongLevel:10,
              type:15,
              value:0.2
            },
            {
              bingzhong:1,
              bingzhongLevel:12,
              type:15,
              value:0.6
            }, 
            ]
          },
          {
            title:'殚心',
            levelMax:10,
            level:0,
            xingchenUnit:[160,160],
            qidiUnit:[70,70],
            tianzunUnit:[300,400],
            qishenUnit:[0,0],
            timeUnit:[150,175],
            isNeedQishen:false,
            shuxing:[{
              bingzhong:1,
              type:12,
              value:1
            }
            ]
          },
          {
            title:'无咎',
            levelMax:10,
            level:0,
            xingchenUnit:[270,680],
            qidiUnit:[120,200],
            tianzunUnit:[600,900],
            qishenUnit:[0,0],
            timeUnit:[200,300],
            isNeedQishen:false,
          },
          {
            title:'麒麟火炬',
            isLock:true
          },
        ],
       },
       {
        index:4,
        title:'绰韬',
        main:[
          {
            title:'伟岸',
            levelMax:10,
            level:0,
            xingchenUnit:[440,590],
            qidiUnit:[190,250],
            tianzunUnit:[0,0],
            qishenUnit:[0,0],
            timeUnit:[120,150],
            isNeedQishen:false,
          },
          {
            title:'鸿土',
            isLock:true
          },
          {
            title:'睚眦',
            isLock:true
          },
          {
            title:'毕呈',
            isLock:true
          },
          {
            title:'盖世',
            isLock:true
          },
          {
            title:'传胤',
            isLock:true
          },
          {
            title:'麒麟御甲',
            isLock:true
          },
        ],
       },
    ],
    adOnceShow:false,
    winWidth: 0,
    winHeight: 0,
    currentTab: 0,
    resultStr:"请注意：1、未知的区域不会参与计算，2、每个天尊的计算是独立的，为防止录入的数据丢失，如果是已经提升的等级，主公们需要手动保存为已提升数据，模拟提升切换tab再返回 之前录入的数据会被重置为上一次保存的已提升数据"
  },
  swichNav: function( e ) {
    var that = this;
    if( this.data.currentTab === e.target.dataset.current ) {
        return false;
    } else {
        var currentData = JSON.parse(JSON.stringify(this.data.qibingData));
        if (e.target.dataset.current == 1) {
            currentData = JSON.parse(JSON.stringify(this.data.gongnuData));
        }else if (e.target.dataset.current == 2) {
          currentData = JSON.parse(JSON.stringify(this.data.bubingData));
        }else if (e.target.dataset.current == 3) {
          currentData = JSON.parse(JSON.stringify(this.data.chebingData));
        }
        that.setData( {
            currentTab: e.target.dataset.current,
            currentData:currentData
        })
    }
  },
  updateCurrentData:function(){
    var currentData = JSON.parse(JSON.stringify(this.data.qibingData));
        if (this.data.currentTab == 1) {
            currentData = JSON.parse(JSON.stringify(this.data.gongnuData));
        }else if (this.data.currentTab.current == 2) {
          currentData = JSON.parse(JSON.stringify(this.data.bubingData));
        }else if (this.data.currentTab.current == 3) {
          currentData = JSON.parse(JSON.stringify(this.data.chebingData));
        }
        this.setData( {
            currentData:currentData
        })
  },
  bindChange: function( e ) {
 
    var that = this;
    that.setData( { currentTab: e.detail.current });
 
  },
  /**
   * 生命周期函数--监听页面加载
   */
  onLoad: function (options) {
    wx.showLoading({
      title: '正在加载',
    })
    if (app.globalData.openid) {
      this.requestData();
    }else{
      console.log(11);
      var that = this;
      app.loginInfo(function(openid){
        that.requestData();
      });
    }
    if (wx.createInterstitialAd) {
      interstitialAd = wx.createInterstitialAd({
        adUnitId: 'adunit-ebab018239736f52'
      })
      interstitialAd.onLoad(() => {})
      interstitialAd.onError((err) => {})
      interstitialAd.onClose(() => {})
    }
    var that = this;
    wx.getSystemInfo({
      success: function(res) {
          that.setData({
              winWidth: res.windowWidth,
              winHeight: res.windowHeight
          });
        }
      });
  },
  requestData:function(){
    var that = this;
    db.collection('tianzunList').where(
      {
        userId:app.globalData.openid
      }
    ).get({
      success:function(res){
        console.log(res.data);
        wx.hideLoading({
          success: (res) => {},
        })
        if (res.data.length==0) {
           that.updateCurrentData()
        }else{
          const element = res.data[0];
          console.log(element)
          that.parseData(element.userData)
          that.updateCurrentData()
        }
      }
    })
  },
  parseData:function(e){
    for (let index = 0; index < e.qibingData.length; index++) {
      const element = e.qibingData[index];
      if (element.title == '绰韬') {
         const staticData = this.data.qibingData[index];
         if (staticData.main.length != element.main.length) {
             e.qibingData[index]=staticData;
             continue;
         }
      }
      for (let j = 0; j < element.main.length; j++) {
        const data = element.main[j];
        if (data.isLock) {
           const staticData = this.data.qibingData[index].main[j];
           console.log(data+JSON.stringify(staticData));
           if (staticData.isLock) {
              continue;
           }else{
            console.log("modify="+JSON.stringify(staticData));
             e.qibingData[index].main[j] = staticData;
           }
        }
      }
    }
    for (let index = 0; index < e.gongnuData.length; index++) {
      const element = e.gongnuData[index];
      if (element.title == '绰韬') {
        const staticData = this.data.gongnuData[index];
        if (staticData.main.length != element.main.length) {
            e.gongnuData[index]=staticData;
            continue;
        }
     }
      for (let j = 0; j < element.main.length; j++) {
        const data = element.main[j];
        if (data.isLock) {
           const staticData = this.data.gongnuData[index].main[j];
           if (staticData.isLock) {
              continue;
           }else{
             e.gongnuData[index].main[j] = staticData;
           }
        }
      }
    }
    for (let index = 0; index < e.bubingData.length; index++) {
      const element = e.bubingData[index];
      if (element.title == '绰韬') {
        const staticData = this.data.bubingData[index];
        if (staticData.main.length != element.main.length) {
            e.bubingData[index]=staticData;
            continue;
        }
     }
      for (let j = 0; j < element.main.length; j++) {
        const data = element.main[j];
        if (data.isLock) {
           const staticData = this.data.bubingData[index].main[j];
           if (staticData.isLock) {
              continue;
           }else{
             e.bubingData[index].main[j] = staticData;
           }
        }
      }
    }
    for (let index = 0; index < e.chebingData.length; index++) {
      const element = e.chebingData[index];
      if (element.title == '绰韬') {
        const staticData = this.data.chebingData[index];
        if (staticData.main.length != element.main.length) {
            e.chebingData[index]=staticData;
            continue;
        }
     }
      for (let j = 0; j < element.main.length; j++) {
        const data = element.main[j];
        if (data.isLock) {
           const staticData = this.data.chebingData[index].main[j];
           if (staticData.isLock) {
              continue;
           }else{
             e.chebingData[index].main[j] = staticData;
           }
        }
      }
    }
    this.setData({
      qibingData:e.qibingData,
      gongnuData:e.gongnuData,
      bubingData:e.bubingData,
      chebingData:e.chebingData
    })
    
  },
  /**
   * 生命周期函数--监听页面初次渲染完成
   */
  onReady: function () {

  },

  /**
   * 生命周期函数--监听页面显示
   */
  onShow: function () {

  },

  /**
   * 生命周期函数--监听页面隐藏
   */
  onHide: function () {

  },

  /**
   * 生命周期函数--监听页面卸载
   */
  onUnload: function () {

  },

  /**
   * 页面相关事件处理函数--监听用户下拉动作
   */
  onPullDownRefresh: function () {

  },

  /**
   * 页面上拉触底事件的处理函数
   */
  onReachBottom: function () {

  },

  /**
   * 用户点击右上角分享
   */
  onShareAppMessage: function () {

  },
  showAd:function(){
    var that = this;
    if (interstitialAd && this.data.adOnceShow == false) {
      var that = this;
      that.setData({
        adOnceShow:true
       })
      interstitialAd.show().catch((err) => {
       console.error(err)
       that.setData({
        adOnceShow:false
       })  
    })
    }
  },
  moniAction:function(){
     this.showAd();
     var staticData = this.data.qibingData;
     if (this.data.currentTab == 1) {
      staticData = this.data.gongnuData;
     }else if (this.data.currentTab.current == 2) {
      staticData = this.data.bubingData;
     }else if (this.data.currentTab.current == 3) {
      staticData = this.data.chebingData;
     }
     console.log()
     var currentData = this.data.currentData;
     let qidiTotal = 0;
     let qishenTotal = 0;
     let xingchenTotal = 0;
     let tianzunTotal = 0;
     let timeTotal = 0;
     var upArray = [];
     for (let index = 0; index < currentData.length; index++) {
       const e = currentData[index];
       const static_e = staticData[index];
       
       for (let j = 0; j < e.main.length; j++) {
         const element = e.main[j];
         const static_element = static_e.main[j];
         if (element.isLock || static_element.isLock) {
            continue;
         }
         if (index == 0 && j == 7) {
          console.log(JSON.stringify(static_element));
         }
         if (Number(element.level)>Number(static_element.level)) {
            if (element.isNeedQishen) {
                for (let k = static_element.level; k < element.level; k++) {
                  qishenTotal = qishenTotal+Number(static_element.qishenUnit[k])
                }
            }else{
                let maxLevel = element.qidiUnit.length*5;
                for (let k = static_element.level; k < element.level; k++) {
                    qidiTotal = qidiTotal + Number(element.qidiUnit[Math.floor(k/5)]);
                    xingchenTotal = xingchenTotal + Number(element.xingchenUnit[Math.floor(k/5)]);
                    timeTotal = timeTotal + Number(element.timeUnit[Math.floor(k/5)]);
                    tianzunTotal = tianzunTotal + Number(element.tianzunUnit[Math.floor(k/5)]);
                }
            }
         }
       }
     }
     var result = '计算结果：\n需要启迪：'+qidiTotal+'个\n需要星辰：'+xingchenTotal+"个\n需要天尊玉："+tianzunTotal+"个\n需要祈神令："+qishenTotal+'个\n需要加速:'+timeTotal+"小时";
     this.setData({
       resultStr:result
     })
  },
  saveAction:function(){
    this.showAd();
    if (this.data.currentTab == 0) {
      this.setData({
        qibingData:JSON.parse(JSON.stringify(this.data.currentData))
      })
    }
    else if (this.data.currentTab == 1) {
      this.setData({
        gongnuData:JSON.parse(JSON.stringify(this.data.currentData))
      })
    }else if (this.data.currentTab.current == 2) {
      this.setData({
        bubingData:JSON.parse(JSON.stringify(this.data.currentData))
      })
    }else if (this.data.currentTab.current == 3) {
      this.setData({
        chebingData:JSON.parse(JSON.stringify(this.data.currentData))
      })
    }
    wx.showLoading({
      title: '正在保存',
    })
    var that = this;
    db.collection('tianzunList').where(
      {
        userId:app.globalData.openid
      }
    ).get({
      success:function(res){
        console.log(res.data);
        wx.hideLoading({
          success: (res) => {},
        })
        if (res.data.length==0) {
          console.log('数据库找不到新增一条')
          db.collection('tianzunList').add({
            // data 字段表示需新增的 JSON 数据
            data: {
              userId:app.globalData.openid,
              userData:{
                qibingData:that.data.qibingData,
                gongnuData:that.data.gongnuData,
                bubingData:that.data.bubingData,
                chebingData:that.data.chebingData
              }
            },
            success: function(res) {
              // res 是一个对象，其中有 _id 字段标记刚创建的记录的 id
              wx.showToast({
                title: '保存成功',
              })
            }
          })
        }else{
          console.log('需要更新数据库')
          db.collection('tianzunList').where(
            {
              userId:app.globalData.openid
            }
          ).update({
            data: {
              userData:{
                qibingData:that.data.qibingData,
                gongnuData:that.data.gongnuData,
                bubingData:that.data.bubingData,
                chebingData:that.data.chebingData
              }
            },
            success: function(res) {
              // res 是一个对象，其中有 _id 字段标记刚创建的记录的 id
              wx.showToast({
                title: '保存成功',
              })
            }
          })
          
        }
      }
    })
  },
  inputLevel:function(e){
    var index = e.currentTarget.dataset.name;
    let indexArray = String(index).split('-');
    var currentData = this.data.currentData;
    var target = currentData[indexArray[0]].main[indexArray[1]]
    console.log(target)
    if (!target) {
      return;
    }
    if (target.isLock) {
      wx.showToast({
        icon:'none',
        title: '主公稍安勿躁\n小窝还没弄到数据',
      })
      return;
    }
    if (target.isNeedQishen) {
       let maxLevel = target.qishenUnit.length;
       console.log("maxlevel="+maxLevel+"\n nowlevel="+JSON.stringify(e.detail.value))
       if (e.detail.value>maxLevel) {
         wx.showToast({
          icon:'none',
          title: '不得超过'+maxLevel+'级',
         })
         currentData[indexArray[0]].main[indexArray[1]].level = Number(maxLevel);
         this.setData({
          currentData:currentData
        })
         return; 
       }  
       currentData[indexArray[0]].main[indexArray[1]].level = Number(e.detail.value);
       console.log(currentData)
       this.setData({
         currentData:currentData
       })
       
    }else{
      let maxLevel = target.qidiUnit.length * 5;
      if (e.detail.value>maxLevel) {
        wx.showToast({
         icon:'none',
         title: '不得超过'+maxLevel+'级',
        });
        currentData[indexArray[0]].main[indexArray[1]].level = Number(maxLevel);
         this.setData({
          currentData:currentData
        })
        return; 
      } 
      currentData[indexArray[0]].main[indexArray[1]].level = Number(e.detail.value);
       console.log(currentData)
       this.setData({
         currentData:currentData
       }) 
    }
  },
  inputFocus:function(e){
    var index = e.currentTarget.dataset.name;
    let indexArray = String(index).split('-');
    var currentData = this.data.currentData[indexArray[0]].main[indexArray[1]]
    console.log(currentData)
    if (currentData && currentData.isLock) {
      wx.showToast({
        icon:'none',
        title: '主公稍安勿躁\n小窝还没弄到数据',
      })
    }
  }
})